### ISSUE TITLE
improve deploy file

### ISSUE THREAD

**Issue by pleustonpress** [pleustonpress/pleuston.org#1]
The page hosting service like cdn and cf-pages server may need the standard exit code of the Python program to determine whether the web page is successfully built. If it is not successful, it needs to raise an exception or return a non-standard value.

Following enhancements:
 - add standard exit code mappings.
 - add custom exceptions.
 - more environments for cdn services.

**Comment by phil616** [comment]
This is not necessary because cloudflare console will display all the infomation from stdout. if the page build fail, just checkout the log.
however, we have no means to checkout whether the artifact they build is right or wrong.
